name: t_chain_payment_example
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.3
  equatable: ^2.0.5
  badges: ^2.0.3
  flutter_easyloading: ^3.0.5
  currency_formatter: ^2.0.0
  momo_vn: ^2.0.2
  t_chain_payment_sdk:
    git:
      url: https://github.com/tokoinofficial/t-chain-payment-sdk.git
      ref: TW-1121_apply_security_for_app_to_app_and_pos_qr_flow

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
